
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 16 06:03:30 CST 2015
//----------------------------------------------------

package Mini_C_Compiler;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int sbracketizq = 48;
  public static final int toption = 21;
  public static final int amp = 55;
  public static final int endvoodoo = 6;
  public static final int printf = 3;
  public static final int tseparator = 44;
  public static final int tselect = 19;
  public static final int tendfor = 18;
  public static final int floatval = 54;
  public static final int tor = 33;
  public static final int coma = 40;
  public static final int treturn = 10;
  public static final int llaveder = 47;
  public static final int endspell = 9;
  public static final int tif = 11;
  public static final int stringval = 50;
  public static final int tequal = 35;
  public static final int endritual = 7;
  public static final int printval = 5;
  public static final int parder = 43;
  public static final int tdefault = 23;
  public static final int tstart = 39;
  public static final int greaterorequal = 38;
  public static final int tfor = 17;
  public static final int iden = 52;
  public static final int numero = 51;
  public static final int sbracketder = 49;
  public static final int spell = 8;
  public static final int tnot = 34;
  public static final int tand = 32;
  public static final int tendif = 14;
  public static final int menos = 27;
  public static final int EOF = 0;
  public static final int mas = 26;
  public static final int tvoid = 60;
  public static final int twhile = 15;
  public static final int error = 1;
  public static final int tstring = 59;
  public static final int tfloat = 58;
  public static final int tenddefault = 24;
  public static final int tnotequal = 36;
  public static final int por = 28;
  public static final int telse = 13;
  public static final int dospuntos = 45;
  public static final int lessorequal = 37;
  public static final int greater = 30;
  public static final int tendoption = 22;
  public static final int tthen = 12;
  public static final int tinteger = 57;
  public static final int llaveizq = 46;
  public static final int tendselect = 20;
  public static final int assign = 25;
  public static final int characterval = 53;
  public static final int tendwhile = 16;
  public static final int parizq = 42;
  public static final int less = 31;
  public static final int division = 29;
  public static final int startvoodoo = 2;
  public static final int scanf = 4;
  public static final int tend = 41;
  public static final int tchar = 56;
}

